#!/bin/bash

export LEIN_HOME=vendor/lein
export LEIN_ROOT=true

LEIN_BIN=$LEIN_HOME/lein

if [ ! -x $LEIN_BIN ]; then
  mkdir -p $LEIN_HOME
  echo "-> Downloading lein installer ..."
  curl -s https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein -o $LEIN_BIN
  chmod +x $LEIN_BIN
fi

if [ "$1" == "clojars" ]; then
  if [ -n "$BUILD_NUMBER"]; then
    $LEIN_BIN deploy clojars
  else
    echo "BUILD_NUMBER not set!"
    exit 1
  fi
else
  $LEIN_BIN $@
fi
